easy_admin:
    site_name: '<em style="color: #f0f">Au raw admin</em>'
    entities:
        Allergen:
            class: App\Entity\Allergen
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
            edit:
                actions:
                - {name: '-delete'}

        Ingredient:
            class: App\Entity\Ingredient
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
            edit:
                actions:
                - {name: '-delete'}

        Picture:
            class: App\Entity\Picture
            form:
                fields:
                - {property: 'alt'}
                - {property: 'enabled'}
                - {property: 'img_source'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
            edit:
                actions:
                - {name: '-delete'}

        Product:
            class: App\Entity\Product
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
            edit:
                actions:
                - {name: '-delete'}

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
            edit:
                actions:
                - {name: '-delete'}

        Unit:
            class: App\Entity\Unit
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
            edit:
                actions:
                - {name: '-delete'}