easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Allergen
        - App\Entity\Ingredient
        - App\Entity\Picture
        - App\Entity\Product
        - App\Entity\Tag
        - App\Entity\Unit
