easy_admin:
    site_name: '<em style="color: #f0f">Au raw admin</em>'
    entities:
        Allergen:
            class: App\Entity\Allergen
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
                fields:
                - {property: 'title'}
                - {property: 'created_at'}
                - {property: 'updated_at'}
            edit:
                actions:
                - {name: '-delete'}

        Ingredient:
            class: App\Entity\Ingredient
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
                fields:
                - {property: 'title'}
                - {property: 'created_at'}
                - {property: 'updated_at'}
            edit:
                actions:
                - {name: '-delete'}

        Picture:
            class: App\Entity\Picture
            form:
                fields:
                - {property: 'alt'}
                - {property: 'enabled'}
                - {property: 'img_source'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
                fields:
                - {property: 'created_at'}
                - {property: 'updated_at'}
            edit:
                actions:
                - {name: '-delete'}

        Product:
            class: App\Entity\Product
            form:
                fields:
                - {property: 'title'}
                - {property: 'short_description'}
                - {property: 'long_description'}
                - {property: 'price_euro'}
                - {property: 'price_centime'}
                - {property: 'unit'}
                - {property: 'enabled'}
                - {property: 'allergens'}
                - {property: 'ingredients'}
                - {property: 'tags'}
                - { property: 'iconFile', type: 'file' }
                - { property: 'imageFile', type: 'file' }
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
                fields:
                - { property: 'title' }
                - { property: 'enabled' }
                - {property: 'created_at'}
                - {property: 'updated_at'}
                - {property: 'price_euro'}
                - {property: 'price_centime'}
                - { property: 'icon', type: 'image', base_path: '.%app.path.product_images%' }
                - { property: 'image', type: 'image', base_path: '.%app.path.product_images%' }
            edit:
                actions:
                - {name: '-delete'}

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
                - {property: 'products'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
                fields:
                - {property: 'title'}
                - {property: 'created_at'}
                - {property: 'updated_at'}
                - {property: 'enabled'}
                - {property: 'products'}
            edit:
                actions:
                - {name: '-delete'}

        Unit:
            class: App\Entity\Unit
            form:
                fields:
                - {property: 'title'}
                - {property: 'enabled'}
            list:
                actions:
                - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                - {name: '-delete'}
                fields:
                - {property: 'title'}
                - {property: 'created_at'}
                - {property: 'updated_at'}
            edit:
                actions:
                - {name: '-delete'}