easy_admin:
    entities:
        Allergen:
            class: App\Entity\Allergen
            form:
                fields:
                - {property: 'title'}
                - {property: 'archived'}
                - {property: 'products'}

        Ingredient:
            class: App\Entity\Ingredient
            form:
                fields:
                - {property: 'title'}
                - {property: 'archived'}
                - {property: 'products'}

        Picture:
            class: App\Entity\Picture
            form:
                fields:
                - {property: 'alt'}
                - {property: 'archived'}
                - {property: 'img_source'}
                - {property: 'products'}

        Product:
            class: App\Entity\Product
            form:
                fields:
                - {property: 'title'}
                - {property: 'archived'}

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                - {property: 'title'}
                - {property: 'archived'}
                - {property: 'products'}

        Unit:
            class: App\Entity\Unit
            form:
                fields:
                - {property: 'title'}
                - {property: 'archived'}
                - {property: 'products'}
